### ISSUE TITLE
Transformation to API requests is funky 

### ISSUE THREAD

**Issue by nikhilshinday** [georgegebbett/pulumi-stripe#1]
hey @georgegebbett! Thanks for making this adapter happen. 

I'm having a weird issue and wondering if you can help me track it down. I have this Stripe Price definition:
```
const hourlyProductPrice = new Price(
      `Hourly Price ${this.stack}`,
      {
        active: true,
        billingScheme: "tiered",
        currency: "usd",
        product: hourlyProduct.id,
        recurring: {
          aggregateUsage: "last_during_period",
          interval: "month",
          intervalCount: 1,
          usageType: "metered",
        },
        tiers: [
          {
            upTo: 15,
            flatAmountDecimal: "0.0" as unknown as number,
            unitAmountDecimal: "0.0" as unknown as number,
          },
          { upTo: -1, flatAmount: 0, unitAmount: 600 },
        ],
        tiersMode: "graduated",
      },
    );
```
and when I run `pulumi up`, I get the following error: 
```
Diagnostics:
  pulumi:pulumi:Stack (infra-testing):
    error: update failed

    [ERROR] Request error from Stripe (status 400): {"status":400,"message":"An entry in the tiers array is missing an amount.","param":"amount","request_id":"req_s7vruzVqmGR0xD","request_log_url":"https://dashboard.stripe.com/test/logs/req_s7vruzVqmGR0xD?t=1700708948","type":"invalid_request_error"}

  stripe:index:Price (BuildBetter Hourly Price testing):
    error: 1 error occurred:
    	* {"status":400,"message":"An entry in the tiers array is missing an amount.","param":"amount","request_id":"req_s7vruzVqmGR0xD","request_log_url":"https://dashboard.stripe.com/test/logs/req_s7vruzVqmGR0xD?t=1700708948","type":"invalid_request_error"}
```

and when I follow that stripe request URL, the request body looks like:
```
{
  "active": "true",
  "recurring": {
    "interval": "month",
    "aggregate_usage": "last_during_period",
    "usage_type": "metered",
    "interval_count": "1"
  },
  "billing_scheme": "tiered",
  "currency": "usd",
  "tax_behavior": "unspecified",
  "tiers": {
    "0": {
      "up_to": "15"
    },
    "1": {
      "unit_amount": "600",
      "up_to": "inf"
    }
  },
  "product": "prod_P3XHSpmAW5vFxk",
  "tiers_mode": "graduated"
}
```

two weird things are happening:
1. the `tiers` field is being turned into a mapping. It seems like Stripe accepts that JSON format, though
2. the first element of the `tiers` array is omitting the flat_amount and unit_amount fields, likely because they evaluate to zero. 

Do you have any thoughts on why this might be happening?

**Comment by georgegebbett** [comment]
Hey @nikhilshinday - it looks like the upstream Terraform provider has had an update which fixed a bug in this behaviour. 

I will regenerate the Pulumi provider from the new Terraform one and publish to NPM at some point today, hopefully this should resolve the behaviour you're seeing.

**Comment by georgegebbett** [comment]
I have won my battle with my Github Actions and published a new version of the package to NPM - if you install v0.0.22 you will be using a provider that is derived from the latest version of the Terraform provider. 

Let me know if this solves your issue - if not it will be a more involved fix!

**Comment by georgegebbett** [comment]
Glad to hear it!
